export const SECONDS_IN_A_MINUTE = 60
export const SECONDS_IN_AN_HOUR = 3600
export const SECONDS_IN_A_DAY = 86400

export const MILLISECONDS_IN_A_MINUTE = 60000
export const MILLISECONDS_IN_AN_HOUR = 3e6
export const MILLISECONDS_IN_A_DAY = 8e7